artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1Ewma3-jtDX-7JpZDKzPGqMZTEbo_rXVx/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

training:
  root_dir: artifacts/training
  data_dir: artifacts/data_ingestion/casting_data/train
  model_filename: model.keras

evaluation:
  root_dir: artifacts/evaluation
  model_path: artifacts/training/model.keras
  mlflow_uri: https://dagshub.com/viketanrevankar108/Automated-Quality-Inspection-of-Casting-Products-Using-Deep-Learning.mlflow
  data_dir: artifacts/data_ingestion/casting_data/test

prediction:
  root_dir: artifacts/predictions
  model_path: artifacts/training/model.keras
  class_names: ['def_front','ok_front']
  img_size: 256



